name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
   - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies & build
        run: |
          npm ci
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
